### ISSUE TITLE
UPgrade to 348 breaks it all

### ISSUE THREAD

**Issue by ungentilgarcon** [gzenux/asuswrt-rtn18u#1]
Hello,

tried to upgrade to 348, yet it makes the whole router buggy, there is an issue with vpn clients for instance, did you try it yourself?

**Comment by gzenux** [comment]
No fully tested, only some issues are fixed during the simple trial use before the firmware is released.
Which version did you upgrade from? Is there any step to reproduce this issue after the router restore to default?

**Comment by ungentilgarcon** [comment]
well, can you try the vpn clients on yours? there used to be 5, and they got broken, issuing a nvram clear didn't solve this.

also it said something like subnet anavailable

**Comment by greno4ka** [comment]
Yesterday I've installed the last release on my rt-n18u. VPN client works good. No problems. But there is a problem with mounting HDD. I plug it in usb3 or usb2 slot, no matter, it can't mount it.

There are several people, who have the same problem: https://www.snbforums.com/threads/the-infamous-usb-3-0-issue-ok-on-stock-vs-not-ok-on-merlin.50333/

On my stock firmware all was good. On dd-wrt also it was working.

**Comment by greno4ka** [comment]
Sorry for so long awaiting of my answer, today I tried to connect my 16gb usb stick and seems that it's work pretty nice. After that, i tried not previous 2tb usb hdd, but other 500gb usb-hdd and it doesn't work too. Of course, 16gb stick works on both usb ports, and hdd doesnt work on both usb ports. But they are successfully detected and get unmount state.

Then I performed an experiment:
The stick was in fat32, when it was working with router. I formatted it in ext4, using gparted, and it became not mounted as all my hdds. So the problem not in power, but in file system, as I think.

Firmware version: 384.8_2 - last stable.
I attached screens of web gui, If you want me to perform some commands in shell, I can do it.

Also attach screen of my partition of usb stick that doesn't work.

![screen02](https://user-images.githubusercontent.com/8567537/51967498-8c505700-2480-11e9-8d3a-0e582c79f228.png)
![2019-01-30 11 11 16](https://user-images.githubusercontent.com/8567537/51967291-fcaaa880-247f-11e9-87ac-ce89695e3cc8.png)
![2019-01-30 11 11 59](https://user-images.githubusercontent.com/8567537/51967292-fcaaa880-247f-11e9-9310-ed893408c284.png)

**Comment by greno4ka** [comment]
Now I performed test to prove that problem in working with ext file system. I formatted my hdd in fat32 and it works pretty nice. So, if you want to reproduce problem, use the ext4 type.

![screen02](https://user-images.githubusercontent.com/8567537/51968164-52805000-2482-11e9-9e48-d0e474a9d7c5.png)
![2019-01-30 11 27 11](https://user-images.githubusercontent.com/8567537/51968160-4f855f80-2482-11e9-833c-7369c6e3b4da.png)

**Comment by gzenux** [comment]
I can reproduce this issue now, and it should be an ext4 filesystem compatibility issue.
The root cause is new filesystem feature 'metadata_csum' enabled by newer tool in linux host but it's unsupported by rt-n18u.

This should be the same issue as the post: https://www.snbforums.com/threads/ext4-drive-doesnt-mount.45637/

Symptom analysis:
To make sure the same root cause, login router via SSH and then use the ext4 usb disk plug it in router, type command:
	\# `dmesg`

If you see the following message, it should be the same issue caused by unsupport metadata_csum feature:(please see the references at the end of this post)
EXT4-fs (sda1): couldn't mount RDWR because of unsupported optional features (400)

The metadata checksumming code started going into mainline in Linux 3.5 but rt-n18u used 2.6 kernel.
The workaround is to disable metadata checksum feature on ext4 filesystem.
**Please also note that this workaround only aims my reproduced issue and it will alter your disk, remember to backup your important data.**

- Step1. Plug usb stick in linux host and unmount ext4 partition. (assume the usb stick is **/dev/sdc** and ext4 partition is **/dev/sdc1** in linux host)

- Step2. Remove metadata_csum, 64bit and has_journal features
	\# `e2fsck -f /dev/sdc1`
	\# `tune2fs -O ^metadata_csum,^64bit,^has_journal /dev/sdc1`

- Step3. Converting the filesystem to 32-bit.
	\# `resize2fs -s /dev/sdc1`

- Step4. Add journal feature back
	\# `tune2fs -O has_journal /dev/sdc1`

Remove usb stick form linux host and plug it in router after all above steps are done without any error.
You should see the disk is mounted on web gui.

References:
- https://unix.stackexchange.com/questions/287159/linux-couldnt-mount-rdwr-because-of-unsupported-optional-features-400
- https://ext4.wiki.kernel.org/index.php/Ext4_Metadata_Checksums

**Comment by greno4ka** [comment]
Sorry again, for a long silence.
Made a usb stick as ext4, run dmesg, got predicted output.

I run all your commands and got mounted usb stick with ext4 fs. IT WORKS!!!

YOU'RE GENIUS!!! Thanks a lot for such fast and good answers! Sorry for my offtopic messages in this issue.

I vote for closing this issue as WORKSFORME, because I use many cool features of this firmware and except this solved problem with ext4 fs, I can't see any other problems.

**Comment by gzenux** [comment]
Thank you for interesting in this project.

Unfortunately the 384.8_2 probably could be the last time to sync with asuswrt-merlin since there is no prebuilt binary available from asus for newer codebase.

There is no plan for next release for now and I would try to backport the updates/bug-fixes of open-source components from asuswrt-merlin if I could.

I close this issue since the 384.8_2 seems to work without any fatal issue.

Best Regards
